CREATE TABLE Users (
  uid INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  user VARCHAR(255) NOT NULL, 
  realname  VARCHAR(255) NOT NULL,
  password VARCHAR(255),
  isadmin BIT
);

CREATE TABLE Quotes (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  quote VARCHAR(2048) NOT NULL,
  date VARCHAR(255) NOT NULL,
  user INT NOT NULL,
  context VARCHAR(8000),
  FOREIGN KEY (user) REFERENCES Users(uid)
);
  

